apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: todo-db-creds-es
  namespace: todo-app
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager

  target:
    name: todo-app-db-secret   # this matches deployment
    creationPolicy: Owner

  data:
    - secretKey: DB_USER
      remoteRef:
        key: rds!db-bd7724bb-3fe7-42d6-b09e-54502c56e30c # 🔴 PUT YOUR REAL NAME
        property: username

    - secretKey: DB_PASSWORD
      remoteRef:
        key: rds!db-bd7724bb-3fe7-42d6-b09e-54502c56e30c   # 🔴 same here
        property: password
