apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: todo-db-creds-es
  namespace: todo-app
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager

  target:
    name: todo-app-db-secret   # this matches deployment
    creationPolicy: Owner

  data:
    - secretKey: DB_USER
      remoteRef:
        key: rds!db-29bed19f-79ff-4818-b2b8-b588614c6cb2 # 🔴 PUT YOUR REAL NAME
        property: username

    - secretKey: DB_PASSWORD
      remoteRef:
        key: rds!db-29bed19f-79ff-4818-b2b8-b588614c6cb2   # 🔴 same here
        property: password
