apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-app-config
  namespace: todo-app
data:
  APP_ENV: "prod"
  LOG_LEVEL: "info"
  FEATURE_DELETE_CONFIRM: "true"
  METRICS_ENABLED: "true"
  API_TIMEOUT_SECONDS: "5"
