apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter-resources
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "40"
spec:
  project: platform

  source:
    repoURL: https://gitlab.com/learning-group1580903/Learning-project.git
    targetRevision: main
    path: clusters/prod/addons/karpenter-resources

  destination:
    server: https://kubernetes.default.svc
    namespace: karpenter

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
