apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-app-hpa
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: platform   # ✅ must match AppProject metadata.name
  destination:
    server: https://kubernetes.default.svc
    namespace: todo-app
  source:
    repoURL: https://gitlab.com/learning-group1580903/Learning-project.git
    targetRevision: main
    path: clusters/prod/apps/todo-app-hpa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
