apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-folder
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "45"
spec:
  project: platform

  source:
    repoURL: https://gitlab.com/learning-group1580903/Learning-project.git
    targetRevision: main
    path: clusters/prod/addons/monitoring
    directory:
      recurse: true

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
