apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-image-updater-ecr-basic-auth
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager

  target:
    name: ecr-basic-auth
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "057165950410.dkr.ecr.us-east-1.amazonaws.com": {
                "username": "AWS",
                "password": "{{ .password }}",
                "auth": "{{ printf "%s:%s" "AWS" .password | b64enc }}"
              }
            }
          }

  data:
    - secretKey: password
      remoteRef:
        key: eksdemo2/prod/argocd-image-updater/ecr-login-password
        property: password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None