apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecr-token-rotator
  namespace: argocd
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::057165950410:role/eksdemo2-ecr-token-rotator-irsa
