apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-irsa
  namespace: external-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "6"
    eks.amazonaws.com/role-arn: arn:aws:iam::057165950410:role/eksdemo2-external-secrets-secretsmanager-irsa
